### ISSUE TITLE
No separate development/production webpack configurations for DOM delegate

### ISSUE THREAD

**Issue by kass-kass** [ScalablePixelStreaming/Frontend#4]
Dear maintainers,

From my limited web development knowledge, I understand it's common to have separate development/production configurations for webpack, as described in their official documentation [here](https://webpack.js.org/guides/production/).

This is usually done with a common `webpack.common.js` for both configurations, and specific configuration options split between `webpack.prod.js` and `webpack.dev.js`. 

In the source of the DOM delegate, there is currently only one configuration, which limits some things. For example, it uses `devtool: 'inline-source-map'`, which is helpful during development, but generates large pages. For a a production website, it would best to disable that.

Is there any specific reasons split configurations aren't used for the DOM delegate? If not, I can spend some time to make them and update the build scripts to have `dev` run on `npm start`, and `prod` on `npm build`. 

Wanted to ask just in case, to avoid doing it and having the pull request rejected. 

Let me know and thank you :)

**Comment by lukehb** [comment]
Yeah, let's do this.

I recently did this same work in official Epic frontend here: 

https://github.com/EpicGames/PixelStreamingInfrastructure/blob/master/Frontend/library/webpack.common.js
https://github.com/EpicGames/PixelStreamingInfrastructure/blob/master/Frontend/library/webpack.dev.js
https://github.com/EpicGames/PixelStreamingInfrastructure/blob/master/Frontend/library/webpack.prod.js

@kass-kass Happy to accept a PR if you want to implement this similar to the links above?

**Comment by kass-kass** [comment]
@lukehb Sounds good, will make the changes and open a PR during the next week.

**Comment by dan-tw** [comment]
@kass-kass Is this something you're still interested in doing?
